### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by Brianbla** [GHDeveloperMS/caption-this#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by labpani** [comment]
What does this button do?

**Comment by russest3** [comment]
hello

**Comment by w-marino** [comment]
Comment

**Comment by jrich003** [comment]
I got issues

**Comment by jasonmiller1556** [comment]
Jeff Birzes is my hero.

**Comment by BryceTant** [comment]
Hi

**Comment by kalsundar** [comment]
some options like settings are not shown for me

**Comment by mk4717** [comment]
git github

**Comment by jgiroso** [comment]
Hello :)

**Comment by brandonbushong11** [comment]
Hello

**Comment by calvintran2020** [comment]
Good morning

**Comment by JCappucc** [comment]
the magic is real

**Comment by jonchen8** [comment]
hi

**Comment by acalbazana** [comment]
hello world
